CREATE TABLE Chef (
Chef_ID INT AUTO_INCREMENT PRIMARY KEY,
Chef_Name VARCHAR (50),
Chef_Specialty VARCHAR (50),
date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE Dishes (
Dishes_ID  INT AUTO_INCREMENT PRIMARY KEY,
Dishes_Menu VARCHAR (50),
Chef_ID VARCHAR (50),
Dishes_cost INT,
date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP

)